theme: jekyll-theme-cayman
title: [Reading Group 2020 School of Informatics Computing and Cyber Systems Northern Arizona University]
description: [A short description of your site's purpose]
github:
  is_project_page: false
